spring:
  application:
    name: heima-ai
  ai:
    mcp:
      server:
        enabled: true
        transport: stdio
        name: heima-ai-mcp-server
        version: 1.0.0
    ollama:
      base-url: ${OLLAMA_BASE_URL:http://localhost:11434}
      chat:
        model: ${OLLAMA_MODEL:deepseek-r1:1.5b}
    openai:
      base-url: ${OPENAI_BASE_URL:https://dashscope.aliyuncs.com/compatible-mode}
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: ${OPENAI_CHAT_MODEL:qwen-max-latest}
      embedding:
        options:
          model: ${OPENAI_EMBEDDING_MODEL:text-embedding-v3}
          dimensions: ${OPENAI_EMBEDDING_DIMENSIONS:1024}
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DATABASE_URL:jdbc:mysql://localhost:3306/itheima?serverTimezone=Asia/Shanghai&useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&tinyInt1isBit=false&allowPublicKeyRetrieval=true&allowMultiQueries=true&useServerPrepStmts=false}
    username: ${DATABASE_USERNAME:root}
    password: ${DATABASE_PASSWORD:root}
logging:
  level:
    org.springframework.ai: ${LOG_LEVEL_AI:debug}
    com.itheima.ai: ${LOG_LEVEL_APP:debug}
    
# MCP 配置
